apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: {{ .Values.replicas | int }}
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-container
          image: {{ .Values.image }}
          ports:
            - containerPort: 80
              name: http-web-svc
      restartPolicy: Always
